[profile.default]
src = 'src'
out = 'out'
test = 'test'
script='script'
broadcast='broadcast'
libs = ['lib', 'node_modules']
cache_path  = 'forge-cache'
gas_reports = ["*"]
optimize = false # set to true to enable optimizer
via_ir = false # set to true to enable IR compiler
# optimize_runs = 20000 
solc = '0.8.15'
fs_permissions = [{ access = "read-write", path = "./addresses/"}, { access ="read", path="./out/"}]

# ! Profile not overriding default profile
# Need to see why (potentially https://github.com/foundry-rs/foundry/issues/3120)
[profile.prod]
optimize = true
via_ir = true
optimize_runs = 20000 

[rpc_endpoints]
fuji = "${FUJI_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"

[etherscan]
fuji = { key = "${SNOWTRACE_API_KEY}" }
mumbai = { key = "${POLYSCAN_API_KEY}" }
