[profile.default]
src = 'src'
out = 'out'
test = 'test'
script='script'
broadcast='broadcast'
libs = ['lib', 'node_modules']
cache_path  = 'forge-cache'
fs_permissions = [{ access = "read-write", path = "./addresses/"}, { access ="read", path="./out/"}]
solc = '0.8.19'
gas_reports = ["*"]
optimize = false # set to true to enable optimizer
via_ir = false # set to true to enable IR compiler
ffi = true 

[profile.prod]
optimize = true
via_ir = true
optimizer_runs = 30000 

[rpc_endpoints]
fuji = "${FUJI_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"

[etherscan]
fuji = { key = "${SNOWTRACE_API_KEY}" }
mumbai = { key = "${POLYSCAN_API_KEY}" }

[fmt]
line_length = 120
multiline_func_header = "params_first"
number_underscore="thousands"
# handle sorting of imports